uglifyjs \
jszip.framework.js \
jszip-utils.framework.js \
gl-matrix.framework.js \
webgl-obj-loader.js \
framework/curlify.js \
framework/glutils.js \
framework/sys.js \
framework/fps.js \
framework/animator.js \
framework/scene.js \
framework/object.js \
framework/quad.js \
framework/plane.js \
framework/focusable.js \
framework/rectangle.js \
framework/image.js \
framework/masked_image.js \
framework/fbo_object.js \
framework/masked_fbo_object.js \
framework/button.js \
framework/sprite.js \
framework/carousel.js \
framework/carousel_vertical.js \
framework/scrollable.js \
framework/text.js \
framework/jsonfile.js \
framework/video.js \
framework/mesh.js \
framework/main.js \
-o curlify.min.js \
-m \
-c \
--comments \
--screw-ie8
